name = "ReachabilityBenchmarks"
uuid = "a4785ef3-4c78-58ec-bbba-68644ee365c0"
version = "0.0.1"

[deps]
ReachabilityBase = "379f33d0-9447-4353-bd03-d664070e549f"

[compat]
ReachabilityBase = "0.2.5, 0.3"
julia = "1.2"
